### ISSUE TITLE
Apache UIMA requirement

### ISSUE THREAD

**Issue by jeffmax** [tmills/ctakes-docker#32]
I just had a question around requiring UIMA as a separate download- it seems that ctakes comes bundled with the CVD application in /bin. It is also possible to run the default clinical pipeline without downloading UIMA. Is it strictly necessary to to download UIMA separately or is there another reason it is recommended?

**Comment by tmills** [comment]
For this project the UIMA download is necessary to get the UIMA-AS (Asynchronous Scaleout) libraries. Vanilla cTAKES doesn't use AS but I use it for this project to distribute the analysis engines.
