### ISSUE TITLE
cannot use UMLS password because it's now replaced

### ISSUE THREAD

**Issue by chen-yifu** [tmills/ctakes-docker#39]
Hi,
I think the UMLS username/password method is no longer supported. The NIH website states that the new login method is to use a third-party identity provider. Is there a solution to this? Thanks!
![image](https://user-images.githubusercontent.com/45907512/117074249-f69f7400-ace7-11eb-9b70-eaf13f7ad4ff.png)

**Comment by tmills** [comment]
Yes, unfortunately it has broken this repo/container. We are working on a new one.

**Comment by chen-yifu** [comment]
Hi prof. Mills, 

Thanks for your reply! Does this mean there is no other way of using cTAKES with UMLS annotators?

Thanks again,
Yifu

**Comment by tmills** [comment]
cTAKES can be used -- version 4.0.0.1 was recently released, which updated to the new authentication mechanism. I haven't gone through and updated these containers to use it, as I am working on a new architecture which I think will be simpler. I will release that at some point.
