### ISSUE TITLE
Collection Reader Issue + Interesting Story

### ISSUE THREAD

**Issue by MatthewVita** [tmills/ctakes-docker#6]
Hi Tim,

Hope you are well.

So I'll start with the good news. I made a YouTube video overviewing how to set up the cTAKES Docker solution for my volunteer team on the OpenEMR project. I expected like ~3 views on the video... it's up to 130 views and a few people have reached out to me saying that it's the easiest way to get up and running. There is even a gentleman playing around with it for his hospital system! Good YouTube SEO I guess!

Now for the not so good news. I'm trying to run the collection reader without the MIST deid stuff and am running into a lot of errors.

Here's the command I'm running:
```
./bin/runRemoteAsyncAE.sh tcp://10.0.2.15:61616 mainQueue -d desc/localDeploymentDescriptorNoDeid.xml -c desc/FilesInDirectoryCollectionReader.xml -o xmis/
```

Here `localDeploymentDescriptorNoDeid.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<analysisEngineDeploymentDescription xmlns="http://uima.apache.org/resourceSpecifier">
  <name>coordinatingDescriptor</name>
  <description/>
  <version>1.0</version>
  <vendor/>
  <deployment protocol="jms" provider="activemq">
    <casPool numberOfCASes="1" initialFsHeapSize="2000000"/>
    <service>
      <inputQueue endpoint="mainQueue" prefetch="0"/>
      <topDescriptor>
          <import location="remoteNoDeid.xml"/>
      </topDescriptor>
      <analysisEngine async="true">
        <scaleout numberOfInstances="1"/>

        <delegates>
            <remoteAnalysisEngine key="remoteFastDescriptor">
             <inputQueue endpoint="mainQueue" />
            </remoteAnalysisEngine>
        </delegates>
        <asyncPrimitiveErrorConfiguration>
          <processCasErrors thresholdCount="0" thresholdWindow="0" thresholdAction="terminate"/>
          <collectionProcessCompleteErrors timeout="0" additionalErrorAction="terminate"/>
      </asyncPrimitiveErrorConfiguration>
      </analysisEngine>
    </service>
  </deployment>
</analysisEngineDeploymentDescription>
```

Here's `remoteFastDescriptor.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<analysisEngineDescription xmlns="http://uima.apache.org/resourceSpecifier">
  <frameworkImplementation>org.apache.uima.java</frameworkImplementation>
  <primitive>false</primitive>
  <delegateAnalysisEngineSpecifiers>
    <delegateAnalysisEngine key="docker-fast-dictionary">
      <import location="/home/matthew/ctakes-docker/desc/docker-fast-dictionary.xml"/>
    </delegateAnalysisEngine>
  </delegateAnalysisEngineSpecifiers>
  <analysisEngineMetaData>
    <name>remoteFastDescriptor</name>
    <description/>
    <version>1.0</version>
    <vendor/>
    <configurationParameters/>
    <configurationParameterSettings/>
    <flowConstraints>
      <fixedFlow>
        <node>docker-fast-dictionary</node>
      </fixedFlow>
    </flowConstraints>
    <fsIndexCollection/>
    <capabilities>
      <capability>
        <inputs/>
        <outputs/>
        <languagesSupported/>
      </capability>
    </capabilities>
  <operationalProperties>
      <modifiesCas>true</modifiesCas>
      <multipleDeploymentAllowed>true</multipleDeploymentAllowed>
      <outputsNewCASes>false</outputsNewCASes>
    </operationalProperties>
  </analysisEngineMetaData>
  <resourceManagerConfiguration/>
</analysisEngineDescription>
```

I get a bunch of errors. One of which is `Caused by: java.lang.ClassNotFoundException: org.apache.ctakes.core.cr.FilesInDirectoryCollectionReader`, which is telling.

If I remove the collection read portion of the command, I see this error:

```
Attempting to deploy desc/localDeploymentDescriptorNoDeid.xml ...
Service:Aggregate with de-identification Initialized. Ready To Process Messages From Queue:mainQueue
UIMA AS Service Initialization Complete
Error on process CAS call to remote service:
org.apache.uima.aae.error.UimaEEServiceException: org.apache.uima.aae.error.UimaAsDelegateException: ----> Controller:/Aggregate with de-identification Received Exception  on CAS:-418c09cf:15e0100dd20:-7ffa From Delegate:remoteFastDescriptor

```

**Comment by MatthewVita** [comment]
```
        <delegates>
            <remoteAnalysisEngine key="remoteFastDescriptor">
             <inputQueue endpoint="mainQueue" />
            </remoteAnalysisEngine>
        </delegates>
```

Originally had `myQueueName`. It should be `mainQueue`, right?

**Comment by tmills** [comment]
This is probably a deficiency in my documentation. To run that collection reader you need to have ctakes jars in your uima classpath so it can see that ctakes class. Prepend the command with:
```UIMA_CLASSPATH=/path/to/ctakes-bin/lib```
and then UIMA will look there for jars to load. That explains the first error, maybe retry and see if that helps?

**Comment by MatthewVita** [comment]
Okay sir. I appreciate the response. I will try this tomorrow after work.

BTW, I have been working on a data parser and modern web UI for the cTAKES output. I think you'll find it to be very interesting/useful. I will post more information and a demo in the coming days!

**Comment by MatthewVita** [comment]
Hi Tim,

Hope you are doing well.

I am happy to say that the UIMA_CLASSPATH variable worked like a charm. I have updated the documentation and put in a PR here: https://github.com/tmills/ctakes-docker/pull/7

BTW, I wanted to share with you the parser I am working on. The idea is that it will eventually be at the end of the pipeline as a subscriber somehow: https://github.com/MatthewVita/cTAKES-Concept-Mention-Parser

-m

**Comment by tmills** [comment]
Great. I've added the info to the relevant section of the readme, so I'll consider this closed. Thanks for the feedback.

**Comment by MatthewVita** [comment]
Hi Tim. Did you see my PR?

**Comment by tmills** [comment]
No, sorry, I missed that. I will undo the commit and grab it.
Tim

**Comment by MatthewVita** [comment]
Thank you sir!
